<Project>
  <PropertyGroup>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <PackageVersion Condition="'$(PackageVersion)' == ''">0.0.0-local</PackageVersion>
    <InformationalVersion>$(PackageVersion)</InformationalVersion>
    <Authors>Victor Baybekov</Authors>
    <Copyright>Copyright (c) 2026 Victor Baybekov (@buybackoff)</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/picollodev/Picollo</PackageProjectUrl>
    <RepositoryUrl>https://github.com/picollodev/Picollo</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Description>Picollo: Performance Instrumentation and Continuous Observation for Low-Level Optimization</Description>
    <PackageTags>picollo;performance;perf;perf_event;perf_event_open;hdr;hdrhistogram;histogram</PackageTags>
    <PackageIcon>Picollo.png</PackageIcon>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <DebugType>embedded</DebugType>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\Picollo.png" Pack="true" PackagePath="\" Visible="false"/>
  </ItemGroup>
</Project>
